import React, { Fragment } from 'react';

export function getModelName() {
    let carModel = [{
        id: 430,
        value: "1"
      }, {
        id: 167,
        value: "2"
      }, {
        id: 73,
        value: "3"
      }, {
        id: 135,
        value: "4"
      }, {
        id: 84,
        value: "5"
      }, {
        id: 259,
        value: "6"
      }, {
        id: 345,
        value: "7"
      }, {
        id: 447,
        value: "8"
      }, {
        id: 516,
        value: "77"
      }, {
        id: 223,
        value: "86"
      }, {
        id: 586,
        value: "100"
      }, {
        id: 12,
        value: "124"
      }, {
        id: 598,
        value: "150"
      }, {
        id: 379,
        value: "155"
      }, {
        id: 658,
        value: "195"
      }, {
        id: 402,
        value: "200"
      }, {
        id: 481,
        value: "210"
      }, {
        id: 274,
        value: "230"
      }, {
        id: 531,
        value: "250"
      }, {
        id: 53,
        value: "300"
      }, {
        id: 448,
        value: "308"
      }, {
        id: 478,
        value: "338"
      }, {
        id: 449,
        value: "348"
      }, {
        id: 380,
        value: "350"
      }, {
        id: 444,
        value: "355"
      }, {
        id: 590,
        value: "400"
      }, {
        id: 288,
        value: "440"
      }, {
        id: 497,
        value: "450"
      }, {
        id: 414,
        value: "458"
      }, {
        id: 411,
        value: "488"
      }, {
        id: 682,
        value: "500"
      }, {
        id: 396,
        value: "540"
      }, {
        id: 458,
        value: "550"
      }, {
        id: 698,
        value: "650"
      }, {
        id: 303,
        value: "718"
      }, {
        id: 88,
        value: "911"
      }, {
        id: 479,
        value: "912"
      }, {
        id: 467,
        value: "928"
      }, {
        id: 580,
        value: "968"
      }, {
        id: 455,
        value: "993"
      }, {
        id: 58,
        value: "1500"
      }, {
        id: 34,
        value: "2500"
      }, {
        id: 476,
        value: "3000"
      }, {
        id: 487,
        value: "3100"
      }, {
        id: 692,
        value: "3200"
      }, {
        id: 258,
        value: "3500"
      }, {
        id: 474,
        value: "5500"
      }, {
        id: 1,
        value: "Grand"
      }, {
        id: 2,
        value: "Ram"
      }, {
        id: 3,
        value: "Sentra"
      }, {
        id: 4,
        value: "Terrain"
      }, {
        id: 5,
        value: "F-150"
      }, {
        id: 6,
        value: "RAV4"
      }, {
        id: 7,
        value: "Expedition"
      }, {
        id: 8,
        value: "Lancer"
      }, {
        id: 9,
        value: "Pathfinder"
      }, {
        id: 10,
        value: "Mazda6"
      }, {
        id: 11,
        value: "Qashqai"
      }, {
        id: 13,
        value: "Escape"
      }, {
        id: 14,
        value: "Outlander"
      }, {
        id: 15,
        value: "Sonata"
      }, {
        id: 16,
        value: "MKZ"
      }, {
        id: 17,
        value: "Mustang"
      }, {
        id: 18,
        value: "Santa"
      }, {
        id: 19,
        value: "Tucson"
      }, {
        id: 20,
        value: "Q50"
      }, {
        id: 21,
        value: "RVR"
      }, {
        id: 22,
        value: "Mazda3"
      }, {
        id: 23,
        value: "Equinox"
      }, {
        id: 24,
        value: "Passat"
      }, {
        id: 25,
        value: "Outback"
      }, {
        id: 26,
        value: "Tiguan"
      }, {
        id: 27,
        value: "Edge"
      }, {
        id: 28,
        value: "X5"
      }, {
        id: 29,
        value: "Accord"
      }, {
        id: 30,
        value: "Cooper"
      }, {
        id: 31,
        value: "CX-3"
      }, {
        id: 32,
        value: "Versa"
      }, {
        id: 33,
        value: "Kicks"
      }, {
        id: 35,
        value: "Boxster"
      }, {
        id: 36,
        value: "Eclipse"
      }, {
        id: 37,
        value: "Elantra"
      }, {
        id: 38,
        value: "GLC"
      }, {
        id: 39,
        value: "Traverse"
      }, {
        id: 40,
        value: "X3"
      }, {
        id: 41,
        value: "Sorento"
      }, {
        id: 42,
        value: "EcoSport"
      }, {
        id: 43,
        value: "Seltos"
      }, {
        id: 44,
        value: "CX-5"
      }, {
        id: 45,
        value: "Ioniq"
      }, {
        id: 46,
        value: "LEAF"
      }, {
        id: 47,
        value: "Corolla"
      }, {
        id: 48,
        value: "Jetta"
      }, {
        id: 49,
        value: "Civic"
      }, {
        id: 50,
        value: "Flex"
      }, {
        id: 51,
        value: "Wrangler"
      }, {
        id: 52,
        value: "Cruze"
      }, {
        id: 54,
        value: "Rogue"
      }, {
        id: 55,
        value: "A4"
      }, {
        id: 56,
        value: "CR-V"
      }, {
        id: 57,
        value: "Insight"
      }, {
        id: 59,
        value: "Pacifica"
      }, {
        id: 60,
        value: "Charger"
      }, {
        id: 61,
        value: "Compass"
      }, {
        id: 62,
        value: "TLX"
      }, {
        id: 63,
        value: "Titan"
      }, {
        id: 64,
        value: "Sportage"
      }, {
        id: 65,
        value: "Forester"
      }, {
        id: 66,
        value: "Explorer"
      }, {
        id: 67,
        value: "Crosstrek"
      }, {
        id: 68,
        value: "Sierra"
      }, {
        id: 69,
        value: "Enclave"
      }, {
        id: 70,
        value: "RX"
      }, {
        id: 71,
        value: "Forte"
      }, {
        id: 72,
        value: "GLA"
      }, {
        id: 74,
        value: "Malibu"
      }, {
        id: 75,
        value: "335i"
      }, {
        id: 76,
        value: "Camry"
      }, {
        id: 77,
        value: "Durango"
      }, {
        id: 78,
        value: "RDX"
      }, {
        id: 79,
        value: "IS"
      }, {
        id: 80,
        value: "Mercedes_BenzGLA"
      }, {
        id: 81,
        value: "Regal"
      }, {
        id: 82,
        value: "Silverado"
      }, {
        id: 83,
        value: "X1"
      }, {
        id: 85,
        value: "Telluride"
      }, {
        id: 86,
        value: "Encore"
      }, {
        id: 87,
        value: "Suburban"
      }, {
        id: 89,
        value: "Fusion"
      }, {
        id: 90,
        value: "Ascent"
      }, {
        id: 91,
        value: "Niro"
      }, {
        id: 92,
        value: "QX60"
      }, {
        id: 93,
        value: "Murano"
      }, {
        id: 94,
        value: "C-Class"
      }, {
        id: 95,
        value: "HR-V"
      }, {
        id: 96,
        value: "Cabriolet"
      }, {
        id: 97,
        value: "SQ5"
      }, {
        id: 98,
        value: "Taurus"
      }, {
        id: 99,
        value: "Sienna"
      }, {
        id: 100,
        value: "Challenger"
      }, {
        id: 101,
        value: "WRX"
      }, {
        id: 102,
        value: "Countryman"
      }, {
        id: 103,
        value: "CX-30"
      }, {
        id: 104,
        value: "Prius"
      }, {
        id: 105,
        value: "C-HR"
      }, {
        id: 106,
        value: "Acadia"
      }, {
        id: 107,
        value: "Sedona"
      }, {
        id: 108,
        value: "Odyssey"
      }, {
        id: 109,
        value: "328d"
      }, {
        id: 110,
        value: "Golf"
      }, {
        id: 111,
        value: "Envision"
      }, {
        id: 112,
        value: "Maxima"
      }, {
        id: 113,
        value: "Tahoe"
      }, {
        id: 114,
        value: "XT5"
      }, {
        id: 115,
        value: "A5"
      }, {
        id: 116,
        value: "ILX"
      }, {
        id: 117,
        value: "E-Series"
      }, {
        id: 118,
        value: "Bolt"
      }, {
        id: 119,
        value: "Pilot"
      }, {
        id: 120,
        value: "Cherokee"
      }, {
        id: 121,
        value: "Kona"
      }, {
        id: 122,
        value: "MKC"
      }, {
        id: 123,
        value: "Altima"
      }, {
        id: 124,
        value: "E-Golf"
      }, {
        id: 125,
        value: "Legacy"
      }, {
        id: 126,
        value: "X2"
      }, {
        id: 127,
        value: "Venue"
      }, {
        id: 128,
        value: "Volt"
      }, {
        id: 129,
        value: "Beetle"
      }, {
        id: 130,
        value: "GLC-Class"
      }, {
        id: 131,
        value: "WRANGLER"
      }, {
        id: 132,
        value: "Impala"
      }, {
        id: 133,
        value: "Impreza"
      }, {
        id: 134,
        value: "GL-Class"
      }, {
        id: 136,
        value: "330I"
      }, {
        id: 137,
        value: "Journey"
      }, {
        id: 138,
        value: "Taos"
      }, {
        id: 139,
        value: "X6"
      }, {
        id: 140,
        value: "Model"
      }, {
        id: 141,
        value: "RS"
      }, {
        id: 142,
        value: "Soul"
      }, {
        id: 143,
        value: "CLA250"
      }, {
        id: 144,
        value: "Highlander"
      }, {
        id: 145,
        value: "CX-9"
      }, {
        id: 146,
        value: "John"
      }, {
        id: 147,
        value: "S5"
      }, {
        id: 148,
        value: "Veloster"
      }, {
        id: 149,
        value: "XC90"
      }, {
        id: 150,
        value: "Rover"
      }, {
        id: 151,
        value: "E-Class"
      }, {
        id: 152,
        value: "ProMaster"
      }, {
        id: 153,
        value: "MDX"
      }, {
        id: 154,
        value: "A-Class"
      }, {
        id: 155,
        value: "Q3"
      }, {
        id: 156,
        value: "Avalanche"
      }, {
        id: 157,
        value: "Trax"
      }, {
        id: 158,
        value: "QX50"
      }, {
        id: 159,
        value: "Continental"
      }, {
        id: 160,
        value: "TrailBlazer"
      }, {
        id: 161,
        value: "ATS"
      }, {
        id: 162,
        value: "Unlisted"
      }, {
        id: 163,
        value: "750LI"
      }, {
        id: 164,
        value: "Metris"
      }, {
        id: 165,
        value: "Tundra"
      }, {
        id: 166,
        value: "4Runner"
      }, {
        id: 168,
        value: "Macan"
      }, {
        id: 169,
        value: "Canyon"
      }, {
        id: 170,
        value: "Forte5"
      }, {
        id: 171,
        value: "Atlas"
      }, {
        id: 172,
        value: "S3"
      }, {
        id: 173,
        value: "Taycan"
      }, {
        id: 174,
        value: "Tacoma"
      }, {
        id: 175,
        value: "Q5"
      }, {
        id: 176,
        value: "ES"
      }, {
        id: 177,
        value: "CLA-Class"
      }, {
        id: 178,
        value: "A3"
      }, {
        id: 179,
        value: "NX"
      }, {
        id: 180,
        value: "G80"
      }, {
        id: 181,
        value: "Camaro"
      }, {
        id: 182,
        value: "XE"
      }, {
        id: 183,
        value: "Sequoia"
      }, {
        id: 184,
        value: "CC"
      }, {
        id: 185,
        value: "SIERRA"
      }, {
        id: 186,
        value: "C300"
      }, {
        id: 187,
        value: "CLA"
      }, {
        id: 188,
        value: "Avalon"
      }, {
        id: 189,
        value: "Romeo"
      }, {
        id: 190,
        value: "GLA250"
      }, {
        id: 191,
        value: "Cayenne"
      }, {
        id: 192,
        value: "K5"
      }, {
        id: 193,
        value: "Vanagon"
      }, {
        id: 194,
        value: "M-Class"
      }, {
        id: 195,
        value: "A7"
      }, {
        id: 196,
        value: "SLK-Class"
      }, {
        id: 197,
        value: "A250"
      }, {
        id: 198,
        value: "QX80"
      }, {
        id: 199,
        value: "Frontier"
      }, {
        id: 200,
        value: "S2000"
      }, {
        id: 201,
        value: "MKX"
      }, {
        id: 202,
        value: "MX-5"
      }, {
        id: 203,
        value: "M5"
      }, {
        id: 204,
        value: "SL-Class"
      }, {
        id: 205,
        value: "Armada"
      }, {
        id: 206,
        value: "Ridgeline"
      }, {
        id: 207,
        value: "Clubman"
      }, {
        id: 208,
        value: "M4"
      }, {
        id: 209,
        value: "COOPER"
      }, {
        id: 210,
        value: "XTS"
      }, {
        id: 211,
        value: "Reatta"
      }, {
        id: 212,
        value: "QX30"
      }, {
        id: 213,
        value: "Arteon"
      }, {
        id: 214,
        value: "F-250"
      }, {
        id: 215,
        value: "Clarity"
      }, {
        id: 216,
        value: "A6"
      }, {
        id: 217,
        value: "F-Pace"
      }, {
        id: 218,
        value: "TT"
      }, {
        id: 219,
        value: "X4"
      }, {
        id: 220,
        value: "cabriolet"
      }, {
        id: 221,
        value: "FJ"
      }, {
        id: 222,
        value: "Bentayga"
      }, {
        id: 224,
        value: "430i"
      }, {
        id: 225,
        value: "IONIQ"
      }, {
        id: 226,
        value: "Gladiator"
      }, {
        id: 227,
        value: "BRZ"
      }, {
        id: 228,
        value: "Panamera"
      }, {
        id: 229,
        value: "XT4"
      }, {
        id: 230,
        value: "SILVERADO"
      }, {
        id: 231,
        value: "QX70"
      }, {
        id: 232,
        value: "Colorado"
      }, {
        id: 233,
        value: "XLR"
      }, {
        id: 234,
        value: "Stinger"
      }, {
        id: 235,
        value: "XF"
      }, {
        id: 236,
        value: "XC60"
      }, {
        id: 237,
        value: "GLC300"
      }, {
        id: 238,
        value: "F-350"
      }, {
        id: 239,
        value: "Promaster"
      }, {
        id: 240,
        value: "F-Type"
      }, {
        id: 241,
        value: "E-Pace"
      }, {
        id: 242,
        value: "G63"
      }, {
        id: 243,
        value: "Ghibli"
      }, {
        id: 244,
        value: "GTI"
      }, {
        id: 245,
        value: "850CI"
      }, {
        id: 246,
        value: "Rio"
      }, {
        id: 247,
        value: "Optima"
      }, {
        id: 248,
        value: "230i"
      }, {
        id: 249,
        value: "Corvette"
      }, {
        id: 250,
        value: "E"
      }, {
        id: 251,
        value: "Bronco"
      }, {
        id: 252,
        value: "Micra"
      }, {
        id: 253,
        value: "Touareg"
      }, {
        id: 254,
        value: "330i"
      }, {
        id: 255,
        value: "Q7"
      }, {
        id: 256,
        value: "CT"
      }, {
        id: 257,
        value: "Convertible"
      }, {
        id: 260,
        value: "Savana"
      }, {
        id: 261,
        value: "S60"
      }, {
        id: 262,
        value: "LS"
      }, {
        id: 263,
        value: "GX"
      }, {
        id: 264,
        value: "GLA-Class"
      }, {
        id: 265,
        value: "S90"
      }, {
        id: 266,
        value: "Miata"
      }, {
        id: 267,
        value: "GLE"
      }, {
        id: 268,
        value: "SL550"
      }, {
        id: 269,
        value: "A8"
      }, {
        id: 270,
        value: "CTS"
      }, {
        id: 271,
        value: "IS250C"
      }, {
        id: 272,
        value: "CLS-Class"
      }, {
        id: 273,
        value: "Z4"
      }, {
        id: 275,
        value: "435i"
      }, {
        id: 276,
        value: "Navigator"
      }, {
        id: 277,
        value: "H2"
      }, {
        id: 278,
        value: "330XI"
      }, {
        id: 279,
        value: "Transit"
      }, {
        id: 280,
        value: "i3"
      }, {
        id: 281,
        value: "500X"
      }, {
        id: 282,
        value: "Renegade"
      }, {
        id: 283,
        value: "Blazer"
      }, {
        id: 284,
        value: "GLE400"
      }, {
        id: 285,
        value: "Dart"
      }, {
        id: 286,
        value: "Focus"
      }, {
        id: 287,
        value: "Ranger"
      }, {
        id: 289,
        value: "COROLLA"
      }, {
        id: 290,
        value: "Corsair"
      }, {
        id: 291,
        value: "GLE-Class"
      }, {
        id: 292,
        value: "Escalade"
      }, {
        id: 293,
        value: "e-tron"
      }, {
        id: 294,
        value: "NV200"
      }, {
        id: 295,
        value: "V90"
      }, {
        id: 296,
        value: "GS"
      }, {
        id: 297,
        value: "Gran"
      }, {
        id: 298,
        value: "Z28"
      }, {
        id: 299,
        value: "Nautilus"
      }, {
        id: 300,
        value: "GLE450"
      }, {
        id: 301,
        value: "228i"
      }, {
        id: 302,
        value: "SLK"
      }, {
        id: 304,
        value: "C/K"
      }, {
        id: 305,
        value: "Other/Unspecified"
      }, {
        id: 306,
        value: "AC"
      }, {
        id: 307,
        value: "G70"
      }, {
        id: 308,
        value: "AMG"
      }, {
        id: 309,
        value: "370Z"
      }, {
        id: 310,
        value: "MX-30"
      }, {
        id: 311,
        value: "SSR"
      }, {
        id: 312,
        value: "428i"
      }, {
        id: 313,
        value: "CLK-Class"
      }, {
        id: 314,
        value: "M2"
      }, {
        id: 315,
        value: "G-Class"
      }, {
        id: 316,
        value: "Yukon"
      }, {
        id: 317,
        value: "Levante"
      }, {
        id: 318,
        value: "S-Class"
      }, {
        id: 319,
        value: "Mirai"
      }, {
        id: 320,
        value: "R8"
      }, {
        id: 321,
        value: "Q8"
      }, {
        id: 322,
        value: "S7"
      }, {
        id: 323,
        value: "4-Series"
      }, {
        id: 324,
        value: "Class"
      }, {
        id: 325,
        value: "E350"
      }, {
        id: 326,
        value: "Q60"
      }, {
        id: 327,
        value: "300S"
      }, {
        id: 328,
        value: "M6"
      }, {
        id: 329,
        value: "SLK350"
      }, {
        id: 330,
        value: "CLS53"
      }, {
        id: 331,
        value: "Passport"
      }, {
        id: 332,
        value: "Polestar"
      }, {
        id: 333,
        value: "Cargo"
      }, {
        id: 334,
        value: "B-Class"
      }, {
        id: 335,
        value: "C350"
      }, {
        id: 336,
        value: "SRX"
      }, {
        id: 337,
        value: "Evora"
      }, {
        id: 338,
        value: "Cayman"
      }, {
        id: 339,
        value: "M3"
      }, {
        id: 340,
        value: "PATHFINDER"
      }, {
        id: 341,
        value: "XC40"
      }, {
        id: 342,
        value: "GLE350D"
      }, {
        id: 343,
        value: "S4"
      }, {
        id: 344,
        value: "Stealth"
      }, {
        id: 346,
        value: "RC"
      }, {
        id: 347,
        value: "TUSCAN"
      }, {
        id: 348,
        value: "BOLT"
      }, {
        id: 349,
        value: "XK8"
      }, {
        id: 350,
        value: "Firebird"
      }, {
        id: 351,
        value: "CLS"
      }, {
        id: 352,
        value: "ML400"
      }, {
        id: 353,
        value: "NAVISTAR"
      }, {
        id: 354,
        value: "XJL"
      }, {
        id: 355,
        value: "NaN"
      }, {
        id: 356,
        value: "S6"
      }, {
        id: 357,
        value: "Xterra"
      }, {
        id: 358,
        value: "EX37"
      }, {
        id: 359,
        value: "UX"
      }, {
        id: 360,
        value: "Spark"
      }, {
        id: 361,
        value: "V60"
      }, {
        id: 362,
        value: "A220"
      }, {
        id: 363,
        value: "Quattroporte"
      }, {
        id: 364,
        value: "GLS"
      }, {
        id: 365,
        value: "LaCrosse"
      }, {
        id: 366,
        value: "Venza"
      }, {
        id: 367,
        value: "M"
      }, {
        id: 368,
        value: "TTS"
      }, {
        id: 369,
        value: "Silvia"
      }, {
        id: 370,
        value: "XT6"
      }, {
        id: 371,
        value: "Q70"
      }, {
        id: 372,
        value: "GLK-Class"
      }, {
        id: 373,
        value: "Fourgon"
      }, {
        id: 374,
        value: "I-Pace"
      }, {
        id: 375,
        value: "C450"
      }, {
        id: 376,
        value: "CLUBMAN"
      }, {
        id: 377,
        value: "ML350"
      }, {
        id: 378,
        value: "Master"
      }, {
        id: 381,
        value: "E400"
      }, {
        id: 382,
        value: "530I"
      }, {
        id: 383,
        value: "A"
      }, {
        id: 384,
        value: "Palisade"
      }, {
        id: 385,
        value: "CT5"
      }, {
        id: 386,
        value: "Série"
      }, {
        id: 387,
        value: "CLA45"
      }, {
        id: 388,
        value: "Eldorado"
      }, {
        id: 389,
        value: "Nova"
      }, {
        id: 390,
        value: "535I"
      }, {
        id: 391,
        value: "240D"
      }, {
        id: 392,
        value: "Coupe"
      }, {
        id: 393,
        value: "F-100"
      }, {
        id: 394,
        value: "325I"
      }, {
        id: 395,
        value: "JK"
      }, {
        id: 397,
        value: "BMW"
      }, {
        id: 398,
        value: "MKT"
      }, {
        id: 399,
        value: "CLS500"
      }, {
        id: 400,
        value: "Coronet"
      }, {
        id: 401,
        value: "Monterey"
      }, {
        id: 403,
        value: "Matrix"
      }, {
        id: 404,
        value: "Testarossa"
      }, {
        id: 405,
        value: "Aventador"
      }, {
        id: 406,
        value: "Cullinan"
      }, {
        id: 407,
        value: "F8"
      }, {
        id: 408,
        value: "Huracan"
      }, {
        id: 409,
        value: "Urus"
      }, {
        id: 410,
        value: "Murcielago"
      }, {
        id: 412,
        value: "MC20"
      }, {
        id: 413,
        value: "720S"
      }, {
        id: 415,
        value: "911T"
      }, {
        id: 416,
        value: "Fit"
      }, {
        id: 417,
        value: "GT"
      }, {
        id: 418,
        value: "Viper"
      }, {
        id: 419,
        value: "570S"
      }, {
        id: 420,
        value: "Gallardo"
      }, {
        id: 421,
        value: "F355"
      }, {
        id: 422,
        value: "S63"
      }, {
        id: 423,
        value: "Ghost"
      }, {
        id: 424,
        value: "G550"
      }, {
        id: 425,
        value: "540C"
      }, {
        id: 426,
        value: "S580"
      }, {
        id: 427,
        value: "NSX"
      }, {
        id: 428,
        value: "F430"
      }, {
        id: 429,
        value: "CT5-V"
      }, {
        id: 431,
        value: "M8"
      }, {
        id: 432,
        value: "EQS"
      }, {
        id: 433,
        value: "California"
      }, {
        id: 434,
        value: "MKIII"
      }, {
        id: 435,
        value: "LX"
      }, {
        id: 436,
        value: "Silver"
      }, {
        id: 437,
        value: "GT-R"
      }, {
        id: 438,
        value: "MT55"
      }, {
        id: 439,
        value: "E63"
      }, {
        id: 440,
        value: "230SL"
      }, {
        id: 441,
        value: "NSX-T"
      }, {
        id: 442,
        value: "F-450"
      }, {
        id: 443,
        value: "GranTurismo"
      }, {
        id: 445,
        value: "G37X"
      }, {
        id: 446,
        value: "S8"
      }, {
        id: 450,
        value: "RX-7"
      }, {
        id: 451,
        value: "Martin"
      }, {
        id: 452,
        value: "MP4-12C"
      }, {
        id: 453,
        value: "Sprinter"
      }, {
        id: 454,
        value: "H1"
      }, {
        id: 456,
        value: "GLS-Class"
      }, {
        id: 457,
        value: "C63"
      }, {
        id: 459,
        value: "SQ8"
      }, {
        id: 460,
        value: "Cobra"
      }, {
        id: 461,
        value: "300C"
      }, {
        id: 462,
        value: "S560"
      }, {
        id: 463,
        value: "745LI"
      }, {
        id: 464,
        value: "GRANTURISMO"
      }, {
        id: 465,
        value: "E450"
      }, {
        id: 466,
        value: "i4"
      }, {
        id: 468,
        value: "E53"
      }, {
        id: 469,
        value: "X7"
      }, {
        id: 470,
        value: "GV60"
      }, {
        id: 471,
        value: "XJR"
      }, {
        id: 472,
        value: "iX"
      }, {
        id: 473,
        value: "NRR"
      }, {
        id: 475,
        value: "M850"
      }, {
        id: 477,
        value: "GL550"
      }, {
        id: 480,
        value: "GTO"
      }, {
        id: 482,
        value: "GLE63"
      }, {
        id: 483,
        value: "New"
      }, {
        id: 484,
        value: "RAM"
      }, {
        id: 485,
        value: "Series"
      }, {
        id: 486,
        value: "WESTFALIA"
      }, {
        id: 488,
        value: "J72"
      }, {
        id: 489,
        value: "GLC63"
      }, {
        id: 490,
        value: "i8"
      }, {
        id: 491,
        value: "Pickup"
      }, {
        id: 492,
        value: "E-Transit"
      }, {
        id: 493,
        value: "750Li"
      }, {
        id: 494,
        value: "Z"
      }, {
        id: 495,
        value: "Chevelle"
      }, {
        id: 496,
        value: "400E"
      }, {
        id: 498,
        value: "240Z"
      }, {
        id: 499,
        value: "Q4"
      }, {
        id: 500,
        value: "Satellite"
      }, {
        id: 501,
        value: "Carnival"
      }, {
        id: 502,
        value: "ID.4"
      }, {
        id: 503,
        value: "CLS63"
      }, {
        id: 504,
        value: "GLE350"
      }, {
        id: 505,
        value: "Bel"
      }, {
        id: 506,
        value: "GV80"
      }, {
        id: 507,
        value: "340i"
      }, {
        id: 508,
        value: "GR"
      }, {
        id: 509,
        value: "350SLC"
      }, {
        id: 510,
        value: "Barracuda"
      }, {
        id: 511,
        value: "S550"
      }, {
        id: 512,
        value: "Yaris"
      }, {
        id: 513,
        value: "Alpina"
      }, {
        id: 514,
        value: "XKR"
      }, {
        id: 515,
        value: "EV6"
      }, {
        id: 517,
        value: "ATS-V"
      }, {
        id: 518,
        value: "GV70"
      }, {
        id: 519,
        value: "C40"
      }, {
        id: 520,
        value: "BOXSTER"
      }, {
        id: 521,
        value: "M440i"
      }, {
        id: 522,
        value: "Maverick"
      }, {
        id: 523,
        value: "04-Mar"
      }, {
        id: 524,
        value: "4runner"
      }, {
        id: 525,
        value: "Supra"
      }, {
        id: 526,
        value: "530i"
      }, {
        id: 527,
        value: "Unimog"
      }, {
        id: 528,
        value: "540I"
      }, {
        id: 529,
        value: "GLE43"
      }, {
        id: 530,
        value: "SL600"
      }, {
        id: 532,
        value: "G500"
      }, {
        id: 533,
        value: "C43"
      }, {
        id: 534,
        value: "540i"
      }, {
        id: 535,
        value: "Karma"
      }, {
        id: 536,
        value: "GT500KR"
      }, {
        id: 537,
        value: "S400"
      }, {
        id: 538,
        value: "750i"
      }, {
        id: 539,
        value: "440i"
      }, {
        id: 540,
        value: "GT500"
      }, {
        id: 541,
        value: "C10"
      }, {
        id: 542,
        value: "Denali"
      }, {
        id: 543,
        value: "250SE"
      }, {
        id: 544,
        value: "Jimmy"
      }, {
        id: 545,
        value: "S65"
      }, {
        id: 546,
        value: "G90"
      }, {
        id: 547,
        value: "DTS"
      }, {
        id: 548,
        value: "F-Series"
      }, {
        id: 549,
        value: "E43"
      }, {
        id: 550,
        value: "K20"
      }, {
        id: 551,
        value: "Road"
      }, {
        id: 552,
        value: "GL350"
      }, {
        id: 553,
        value: "Land"
      }, {
        id: 554,
        value: "3-Series"
      }, {
        id: 555,
        value: "Chevy"
      }, {
        id: 556,
        value: "Carrera"
      }, {
        id: 557,
        value: "GL350BT"
      }, {
        id: 558,
        value: "4WD"
      }, {
        id: 559,
        value: "M550i"
      }, {
        id: 560,
        value: "GLB250"
      }, {
        id: 561,
        value: "G55"
      }, {
        id: 562,
        value: "Integra"
      }, {
        id: 563,
        value: "Five"
      }, {
        id: 564,
        value: "Fleetmaster"
      }, {
        id: 565,
        value: "GL63"
      }, {
        id: 566,
        value: "Chevette"
      }, {
        id: 567,
        value: "SRT"
      }, {
        id: 568,
        value: "Imperial"
      }, {
        id: 569,
        value: "Thunderbird"
      }, {
        id: 570,
        value: "LANCER"
      }, {
        id: 571,
        value: "640i"
      }, {
        id: 572,
        value: "E500"
      }, {
        id: 573,
        value: "325IC"
      }, {
        id: 574,
        value: "berline"
      }, {
        id: 575,
        value: "CLS550"
      }, {
        id: 576,
        value: "E300"
      }, {
        id: 577,
        value: "GLB"
      }, {
        id: 578,
        value: "02-Jan"
      }, {
        id: 579,
        value: "CL63"
      }, {
        id: 581,
        value: "M635"
      }, {
        id: 582,
        value: "KB-2"
      }, {
        id: 583,
        value: "GLC350e"
      }, {
        id: 584,
        value: "Arnage"
      }, {
        id: 585,
        value: "Super"
      }, {
        id: 587,
        value: "XK"
      }, {
        id: 588,
        value: "DUSTER"
      }, {
        id: 589,
        value: "560SEC"
      }, {
        id: 591,
        value: "Seven"
      }, {
        id: 592,
        value: "CX-50"
      }, {
        id: 593,
        value: "CTS-V"
      }, {
        id: 594,
        value: "650i"
      }, {
        id: 595,
        value: "Z4M"
      }, {
        id: 596,
        value: "550i"
      }, {
        id: 597,
        value: "SL55"
      }, {
        id: 599,
        value: "GLS450"
      }, {
        id: 600,
        value: "RLX"
      }, {
        id: 601,
        value: "E550C"
      }, {
        id: 602,
        value: "Custom"
      }, {
        id: 603,
        value: "300E"
      }, {
        id: 604,
        value: "CT6"
      }, {
        id: 605,
        value: "ML63"
      }, {
        id: 606,
        value: "Galaxie"
      }, {
        id: 607,
        value: "SL500"
      }, {
        id: 608,
        value: "SLK300"
      }, {
        id: 609,
        value: "GLA45"
      }, {
        id: 610,
        value: "FUTURAMIC"
      }, {
        id: 611,
        value: "Power"
      }, {
        id: 612,
        value: "Prowler"
      }, {
        id: 613,
        value: "350DL"
      }, {
        id: 614,
        value: "D"
      }, {
        id: 615,
        value: "TR4"
      }, {
        id: 616,
        value: "GranSport"
      }, {
        id: 617,
        value: "XJ"
      }, {
        id: 618,
        value: "560SL"
      }, {
        id: 619,
        value: "Caravan"
      }, {
        id: 620,
        value: "M235i"
      }, {
        id: 621,
        value: "CJ-2A"
      }, {
        id: 622,
        value: "El"
      }, {
        id: 623,
        value: "CUTLASS"
      }, {
        id: 624,
        value: "650I"
      }, {
        id: 625,
        value: "Biscayne"
      }, {
        id: 626,
        value: "Travelall"
      }, {
        id: 627,
        value: "300ZX"
      }, {
        id: 628,
        value: "528i"
      }, {
        id: 629,
        value: "Mark"
      }, {
        id: 630,
        value: "C250"
      }, {
        id: 631,
        value: "Meteor"
      }, {
        id: 632,
        value: "GLI"
      }, {
        id: 633,
        value: "528I"
      }, {
        id: 634,
        value: "C400"
      }, {
        id: 635,
        value: "SKY"
      }, {
        id: 636,
        value: "Spyder"
      }, {
        id: 637,
        value: "SLK250"
      }, {
        id: 638,
        value: "Solstice"
      }, {
        id: 639,
        value: "328I"
      }, {
        id: 640,
        value: "E550"
      }, {
        id: 641,
        value: "Eurovan"
      }, {
        id: 642,
        value: "Eos"
      }, {
        id: 643,
        value: "CL65"
      }, {
        id: 644,
        value: "XJS"
      }, {
        id: 645,
        value: "GLK250"
      }, {
        id: 646,
        value: "924S"
      }, {
        id: 647,
        value: "R32"
      }, {
        id: 648,
        value: "Clipper"
      }, {
        id: 649,
        value: "550I"
      }, {
        id: 650,
        value: "535i"
      }, {
        id: 651,
        value: "Wagoneer"
      }, {
        id: 652,
        value: "Vans"
      }, {
        id: 653,
        value: "Karmann"
      }, {
        id: 654,
        value: "328i"
      }, {
        id: 655,
        value: "740Li"
      }, {
        id: 656,
        value: "Cadenza"
      }, {
        id: 657,
        value: "G37"
      }, {
        id: 659,
        value: "335is"
      }, {
        id: 660,
        value: "MGA"
      }, {
        id: 661,
        value: "500E"
      }, {
        id: 662,
        value: "SENTRA"
      }, {
        id: 663,
        value: "ML-Class"
      }, {
        id: 664,
        value: "Regular"
      }, {
        id: 665,
        value: "GLK350"
      }, {
        id: 666,
        value: "SLK55"
      }, {
        id: 667,
        value: "Genesis"
      }, {
        id: 668,
        value: "SUPER"
      }, {
        id: 669,
        value: "500SEC"
      }, {
        id: 670,
        value: "GL450"
      }, {
        id: 671,
        value: "Fiesta"
      }, {
        id: 672,
        value: "XV"
      }, {
        id: 673,
        value: "Town"
      }, {
        id: 674,
        value: "Liberty"
      }, {
        id: 675,
        value: "Fiero"
      }, {
        id: 676,
        value: "320I"
      }, {
        id: 677,
        value: "JX35"
      }, {
        id: 678,
        value: "CR-Z"
      }, {
        id: 679,
        value: "R-Class"
      }, {
        id: 680,
        value: "Juke"
      }, {
        id: 681,
        value: "GL1800DAK"
      }, {
        id: 683,
        value: "XC70"
      }, {
        id: 684,
        value: "Lucerne"
      }, {
        id: 685,
        value: "FORESTER"
      }, {
        id: 686,
        value: "Accent"
      }, {
        id: 687,
        value: "Appia"
      }, {
        id: 688,
        value: "S55"
      }, {
        id: 689,
        value: "Styleline"
      }, {
        id: 690,
        value: "SC"
      }, {
        id: 691,
        value: "350Z"
      }, {
        id: 693,
        value: "GRAND"
      }, {
        id: 694,
        value: "W150"
      }, {
        id: 695,
        value: "Monte"
      }, {
        id: 696,
        value: "TL"
      }, {
        id: 697,
        value: "Avantime"
      }, {
        id: 699,
        value: "DeVille"
      }, {
        id: 700,
        value: "SLC"
      }, {
        id: 701,
        value: "COMPASS"
      }, {
        id: 702,
        value: "Z3"
      }, {
        id: 703,
        value: "QX55"
      }, {
        id: 704,
        value: "ELANTRA"
      }, {
        id: 705,
        value: "ENVISION"
      }, {
        id: 706,
        value: "Mirage"
      }, {
        id: 707,
        value: "Mazdaspeed3"
      }, {
        id: 708,
        value: "GLS580"
      }, {
        id: 709,
        value: "MXT"
      }, {
        id: 710,
        value: "Mazda5"
      }, {
        id: 711,
        value: "S1000XR"
      }, {
        id: 712,
        value: "Sonic"
      }, {
        id: 713,
        value: "VL800"
      }, {
        id: 714,
        value: "SF90"
      }, {
        id: 715,
        value: "Tribeca"
      }, {
        id: 716,
        value: "G8"
      }, {
        id: 717,
        value: "fortwo"
      }, {
        id: 718,
        value: "540d"
      }, {
        id: 719,
        value: "SCION"
      }, {
        id: 720,
        value: "SLS"
      }, {
        id: 721,
        value: "Patriot"
      }, {
        id: 722,
        value: "Dakota"
      }, {
        id: 723,
        value: "Rio5"
      }, {
        id: 724,
        value: "FordF_550"
      }, {
        id: 725,
        value: "CT4-V"
      }, {
        id: 726,
        value: "CT4"
      }, {
        id: 727,
        value: "FR-S"
      }, {
        id: 728,
        value: "City"
      }, {
        id: 729,
        value: "Q70L"
      }, {
        id: 730,
        value: "Fuso"
      }, {
        id: 731,
        value: "Sedan"
      }, {
        id: 732,
        value: "Hiace"
      }, {
        id: 733,
        value: "MZ3"
      }, {
        id: 734,
        value: "ECLIPSE"
      }, {
        id: 735,
        value: "500-Series"
      }, {
        id: 736,
        value: "Rabbit"
      }, {
        id: 737,
        value: "SL450"
      }, {
        id: 738,
        value: "ELR"
      }, {
        id: 739,
        value: "M550"
      }, {
        id: 740,
        value: "428XI"
      }, {
        id: 741,
        value: "Nitro"
      }, {
        id: 742,
        value: "Express"
      }, {
        id: 743,
        value: "Verano"
      }, {
        id: 744,
        value: "MV-1"
      }, {
        id: 745,
        value: "LC"
      }, {
        id: 746,
        value: "CL-Class"
      }, {
        id: 747,
        value: "NIRO"
      }, {
        id: 748,
        value: "MR2"
      }, {
        id: 749,
        value: "435xDrive"
      }, {
        id: 750,
        value: "E250"
      }, {
        id: 751,
        value: "E55"
      }, {
        id: 752,
        value: "F-PACE"
      }, {
        id: 753,
        value: "Buick"
      }, {
        id: 754,
        value: "Laurentian"
      }, {
        id: 755,
        value: "Sprint"
      }, {
        id: 756,
        value: "LEXUS"
      }, {
        id: 757,
        value: "allroad"
      }, {
        id: 758,
        value: "BRONCO"
      }, {
        id: 759,
        value: "fourgon"
      }, {
        id: 760,
        value: "M240"
      }, {
        id: 761,
        value: "CANYON"
      }, {
        id: 762,
        value: "C"
      }, {
        id: 763,
        value: "SE"
      }, {
        id: 764,
        value: "Cascada"
      }, {
        id: 765,
        value: "530e"
      }, {
        id: 766,
        value: "Willys"
      }, {
        id: 767,
        value: "CLARITY"
      }, {
        id: 768,
        value: "4-series"
      }, {
        id: 769,
        value: "03-Sep"
      }, {
        id: 770,
        value: "OUTLANDER"
      }, {
        id: 771,
        value: "Van"
      }]
    return carModel;
}

export function getBrandName() {
    let brandName = [{
        id: 1,
        value: "Dodge"
      }, {
        id: 2,
        value: "Nissan"
      }, {
        id: 3,
        value: "GMC"
      }, {
        id: 4,
        value: "Ford"
      }, {
        id: 5,
        value: "Toyota"
      }, {
        id: 6,
        value: "Mitsubishi"
      }, {
        id: 7,
        value: "Mazda"
      }, {
        id: 8,
        value: "Fiat"
      }, {
        id: 9,
        value: "Hyundai"
      }, {
        id: 10,
        value: "Lincoln"
      }, {
        id: 11,
        value: "Infiniti"
      }, {
        id: 12,
        value: "Chevrolet"
      }, {
        id: 13,
        value: "Volkswagen"
      }, {
        id: 14,
        value: "Subaru"
      }, {
        id: 15,
        value: "BMW"
      }, {
        id: 16,
        value: "Honda"
      }, {
        id: 17,
        value: "MINI"
      }, {
        id: 18,
        value: "Ram"
      }, {
        id: 19,
        value: "Porsche"
      }, {
        id: 20,
        value: "Mercedes-Benz"
      }, {
        id: 21,
        value: "Kia"
      }, {
        id: 22,
        value: "Jeep"
      }, {
        id: 23,
        value: "Chrysler"
      }, {
        id: 24,
        value: "Audi"
      }, {
        id: 25,
        value: "Acura"
      }, {
        id: 26,
        value: "Buick"
      }, {
        id: 27,
        value: "Lexus"
      }, {
        id: 28,
        value: "Cadillac"
      }, {
        id: 29,
        value: "Tesla"
      }, {
        id: 30,
        value: "Volvo"
      }, {
        id: 31,
        value: "Land"
      }, {
        id: 32,
        value: "Bentley"
      }, {
        id: 33,
        value: "Genesis"
      }, {
        id: 34,
        value: "Jaguar"
      }, {
        id: 35,
        value: "Alfa"
      }, {
        id: 36,
        value: "Maserati"
      }, {
        id: 37,
        value: "Hummer"
      }, {
        id: 38,
        value: "Shelby"
      }, {
        id: 39,
        value: "Polestar"
      }, {
        id: 40,
        value: "Lotus"
      }, {
        id: 41,
        value: "Pontiac"
      }, {
        id: 42,
        value: "International"
      }, {
        id: 43,
        value: "Hino"
      }, {
        id: 44,
        value: "Mercury"
      }, {
        id: 45,
        value: "Ferrari"
      }, {
        id: 46,
        value: "Lamborghini"
      }, {
        id: 47,
        value: "Rolls-Royce"
      }, {
        id: 48,
        value: "McLaren"
      }, {
        id: 49,
        value: "Mercedes-AMG"
      }, {
        id: 50,
        value: "Superformance"
      }, {
        id: 51,
        value: "Freightliner"
      }, {
        id: 52,
        value: "Aston"
      }, {
        id: 53,
        value: "Isuzu"
      }, {
        id: 54,
        value: "Austin-Healey"
      }, {
        id: 55,
        value: "Panther"
      }, {
        id: 56,
        value: "Datsun"
      }, {
        id: 57,
        value: "Plymouth"
      }, {
        id: 58,
        value: "Willys"
      }, {
        id: 59,
        value: "Fisker"
      }, {
        id: 60,
        value: "Factory"
      }, {
        id: 61,
        value: "Saleen"
      }, {
        id: 62,
        value: "Oldsmobile"
      }, {
        id: 63,
        value: "Triumph"
      }, {
        id: 64,
        value: "Saturn"
      }, {
        id: 65,
        value: "Packard"
      }, {
        id: 66,
        value: "MG"
      }, {
        id: 67,
        value: "Lancia"
      }, {
        id: 68,
        value: "Renault"
      }, {
        id: 69,
        value: "Suzuki"
      }, {
        id: 70,
        value: "smart"
      }, {
        id: 71,
        value: "Scion"
      }, {
        id: 72,
        value: "MV-1"
      }, {
        id: 73,
        value: "Saab"
      }]
      return brandName;
}

export function getFuelType() {
    let fuelType = [{
        id: 1,
        value: "Gasoline"
      }, {
        id: 2,
        value: "Other"
      }, {
        id: 3,
        value: "Electric"
      }, {
        id: 4,
        value: "Diesel"
      }]
      return fuelType;
}

export function getDriveTrain() {
    let driveTrain = [{
        id: 1,
        value: "FWD"
      }, {
        id: 2,
        value: "4x4"
      }, {
        id: 3,
        value: "AWD"
      }, {
        id: 4,
        value: "RWD"
      },{
        id: 5,
        value: "4WD"
      }, {
        id: 6,
        value: "NaN"
      }, {
        id: 7,
        value: "2WD"
      }, {
        id: 8,
        value: "4X4"
      }]
      return driveTrain;
}

export function getTransmissionType() {
    let transmissionType = [{
        id: 1,
        value: "Automatic"
      }, {
        id: 2,
        value: "Manual"
      }, {
        id: 3,
        value: "CVT"
      }, {
        id: 4,
        value: "Sequential"
      }]
      return transmissionType;
}

export function getBodyType() {
    let bodyType = [{
        id: 1,
        value: "Van"
      }, {
        id: 2,
        value: "Truck"
      }, {
        id: 3,
        value: "Sedan"
      }, {
        id: 4,
        value: "SUV"
      },{
        id: 5,
        value: "Convertible"
      }, {
        id: 6,
        value: "Hatchback"
      }, {
        id: 7,
        value: "Wagon"
      }, {
        id: 8,
        value: "Coupe"
      }]
      return bodyType;
}